platform :ios, "7.0"

pod 'AFNetworking', '~> 2.2'
pod 'AFNetworkActivityLogger', '~> 2.0'
pod 'Masonry', '~> 0.4'
pod 'SDWebImage', '~> 3.6'
pod 'MBProgressHUD', '~> 0.8'

target :"GoingPlaces Tests", :exclusive => true do
  pod 'Kiwi/XCTest'
end

